import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { registerSW } from 'virtual:pwa-register';
import { defaultData, loadData, saveData } from './lib/db';
import { SCORING_ACTIONS, type AppData, type ScoringActionKey, type TabKey } from './lib/types';
import './styles.css';
registerSW({ immediate: true });
const today = () => new Date().toISOString().slice(0,10);
const tabs: {key:TabKey;label:string}[] = [{key:'home',label:'Home'},{key:'goals',label:'Goals'},{key:'body',label:'Body'},{key:'sleep',label:'Sleep'},{key:'activity',label:'Activity'},{key:'meals',label:'Meals'},{key:'rewards',label:'Rewards'}];
const App=()=>{const [tab,setTab]=useState<TabKey>('home'); const [data,setData]=useState<AppData>(defaultData);
useEffect(()=>{loadData().then(setData)},[]); useEffect(()=>{saveData(data)},[data]);
const todayLog = data.habitLogs.find(d=>d.date===today()) || {date:today(),actions:{}};
const totalPoints=useMemo(()=>data.habitLogs.reduce((s,d)=>s+Object.entries(d.actions).reduce((a,[k,v])=>a+(v?SCORING_ACTIONS[k as ScoringActionKey].points:0),0),0),[data]);
const weekScore=useMemo(()=>{const ws=new Date(); ws.setDate(ws.getDate()-6); const start=ws.toISOString().slice(0,10); return data.habitLogs.filter(d=>d.date>=start).reduce((s,d)=>s+Object.entries(d.actions).reduce((a,[k,v])=>a+(v?SCORING_ACTIONS[k as ScoringActionKey].points:0),0),0)},[data]);
const level=Math.floor(totalPoints/30)+1;
const calTarget=(()=>{const b=data.body;if(!b.weightKg||!b.heightCm||!b.age||!b.sex||!b.activity||!b.goal)return undefined; const bmr=b.sex==='male'?10*b.weightKg+6.25*b.heightCm-5*b.age+5:10*b.weightKg+6.25*b.heightCm-5*b.age-161; const tdee=bmr*b.activity; return Math.round(tdee+(b.goal==='cut'?-500:b.goal==='gain'?300:0));})();
const eaten=data.calorieLogs.filter(c=>c.date===today()).reduce((s,c)=>s+c.kcal,0);
const streak = useMemo(()=>{const days=[...data.habitLogs].sort((a,b)=>b.date.localeCompare(a.date)); let c=0; let cur=new Date(); for(const d of days){const ds=cur.toISOString().slice(0,10); const pts=Object.entries(d.actions).reduce((a,[k,v])=>a+(v?SCORING_ACTIONS[k as ScoringActionKey].points:0),0); if(d.date===ds&&pts>0){c++; cur.setDate(cur.getDate()-1);} else if(d.date<ds) break;} return c;},[data]);
const toggleAction=(k:ScoringActionKey)=>setData(p=>({...p,habitLogs:[...p.habitLogs.filter(d=>d.date!==today()),{...todayLog,actions:{...todayLog.actions,[k]:!todayLog.actions[k]}}]}));
const content = tab==='home'?<div><h2>Week {weekScore} pts · Streak {streak} · Level {level}</h2><div>{Object.entries(SCORING_ACTIONS).map(([k,v])=><button key={k} className={todayLog.actions[k as ScoringActionKey]?'done':''} onClick={()=>toggleAction(k as ScoringActionKey)}>{v.label} (+{v.points})</button>)}</div><p>Calories: {calTarget?`${eaten} / ${calTarget} kcal`:'Fill body stats first'}</p><button onClick={()=>setData(p=>({...p,weeklyTarget:weekScore,archivedWeeklyTargets:[...p.archivedWeeklyTargets,{weekEnding:today(),score:weekScore}]}))}>End week & set new target</button></div>
: tab==='goals'?<div><input placeholder='Weight goal (kg)' type='number' value={data.goals.weightGoalKg??''} onChange={e=>setData(p=>({...p,goals:{...p.goals,weightGoalKg:+e.target.value}}))}/><input placeholder='Weekly score goal' type='number' value={data.goals.weeklyScoreGoal??''} onChange={e=>setData(p=>({...p,goals:{...p.goals,weeklyScoreGoal:+e.target.value}}))}/><textarea placeholder='Daily intention' value={data.goals.dailyIntention} onChange={e=>setData(p=>({...p,goals:{...p.goals,dailyIntention:e.target.value}}))}/><textarea placeholder='Weekly intention' value={data.goals.weeklyIntention} onChange={e=>setData(p=>({...p,goals:{...p.goals,weeklyIntention:e.target.value}}))}/><textarea placeholder='Monthly intention' value={data.goals.monthlyIntention} onChange={e=>setData(p=>({...p,goals:{...p.goals,monthlyIntention:e.target.value}}))}/><p>Weekly review: {weekScore} / {data.goals.weeklyScoreGoal??'-'} pts, days logged {data.habitLogs.length}</p><p>Monthly review: weight trend {(data.weightLogs.at(-1)?.weightKg??0)-(data.weightLogs[0]?.weightKg??0)} kg</p></div>
: tab==='body'?<div>{['weightKg','heightCm','age'].map((f)=><input key={f} placeholder={f} type='number' value={(data.body as any)[f]??''} onChange={e=>setData(p=>({...p,body:{...p.body,[f]:+e.target.value}}))}/)}<select value={data.body.sex??''} onChange={e=>setData(p=>({...p,body:{...p.body,sex:e.target.value as any}}))}><option value=''>Sex</option><option value='male'>Male</option><option value='female'>Female</option></select><select value={data.body.activity??''} onChange={e=>setData(p=>({...p,body:{...p.body,activity:+e.target.value}}))}><option value=''>Activity</option><option value='1.2'>Sedentary</option><option value='1.375'>Light</option><option value='1.55'>Moderate</option><option value='1.725'>Very active</option></select><select value={data.body.goal??''} onChange={e=>setData(p=>({...p,body:{...p.body,goal:e.target.value as any}}))}><option value=''>Goal</option><option value='cut'>Cut</option><option value='maintain'>Maintain</option><option value='gain'>Gain</option></select><button onClick={()=>{if(data.body.weightKg)setData(p=>({...p,weightLogs:[...p.weightLogs,{date:today(),weightKg:data.body.weightKg!}]}));}}>Log weight</button><p>Weight trend: {data.weightLogs.map(w=>`${w.date}: ${w.weightKg}kg`).join(' | ')||'No data'}</p></div>
: tab==='sleep'?<div><input type='time' value={data.sleep.targetBedtime} onChange={e=>setData(p=>({...p,sleep:{...p.sleep,targetBedtime:e.target.value}}))}/><input type='time' value={data.sleep.targetWakeTime} onChange={e=>setData(p=>({...p,sleep:{...p.sleep,targetWakeTime:e.target.value}}))}/><button onClick={()=>setData(p=>({...p,sleep:{...p.sleep,entries:[...p.sleep.entries,{date:today(),hours:8,quality:4,snoring:1}]}}))}>Quick add sleep</button><p>7-day avg hours {(data.sleep.entries.slice(-7).reduce((s,e)=>s+e.hours,0)/(data.sleep.entries.slice(-7).length||1)).toFixed(1)}</p></div>
: tab==='activity'?<div><p>Today: {data.activityPlan[new Date().getDay()]}</p><button onClick={()=>setData(p=>({...p,activityDone:[...new Set([...p.activityDone,today()])]}))}>Mark today's workout done</button><details><summary>Edit week plan</summary>{Object.entries(data.activityPlan).map(([d,v])=><input key={d} value={v} onChange={e=>setData(p=>({...p,activityPlan:{...p.activityPlan,[+d]:e.target.value}}))}/>)}</details></div>
: tab==='meals'?<div><textarea placeholder='Likes' value={data.mealPrefs.likes} onChange={e=>setData(p=>({...p,mealPrefs:{...p.mealPrefs,likes:e.target.value}}))}/><textarea placeholder='Dislikes' value={data.mealPrefs.dislikes} onChange={e=>setData(p=>({...p,mealPrefs:{...p.mealPrefs,dislikes:e.target.value}}))}/><textarea placeholder='Allergies' value={data.mealPrefs.allergies} onChange={e=>setData(p=>({...p,mealPrefs:{...p.mealPrefs,allergies:e.target.value}}))}/><textarea placeholder='Diet style' value={data.mealPrefs.dietStyle} onChange={e=>setData(p=>({...p,mealPrefs:{...p.mealPrefs,dietStyle:e.target.value}}))}/>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>{const dish=data.mealPlan[d]||'';return <div key={d}><input placeholder={`${d} dish`} value={dish} onChange={e=>setData(p=>({...p,mealPlan:{...p.mealPlan,[d]:e.target.value}}))}/><a href={`https://www.koket.se/sok?q=${encodeURIComponent(dish)}`} target='_blank'>Search köket.se</a></div>})}<textarea placeholder='Grocery list' value={data.groceryList} onChange={e=>setData(p=>({...p,groceryList:e.target.value}))}/><button onClick={()=>{const item=prompt('Food item')||'';const kcal=+(prompt('kcal')||0);if(item&&kcal)setData(p=>({...p,calorieLogs:[...p.calorieLogs,{date:today(),item,kcal}]}))}}>Add kcal entry</button></div>
:<div><p>Total points {totalPoints}, Level {level}, next in {30-(totalPoints%30||30)} pts</p>{Array.from({length:10}).map((_,i)=>i+2).map(l=><div key={l}><input value={data.rewards[l]??''} onChange={e=>setData(p=>({...p,rewards:{...p.rewards,[l]:e.target.value}}))} placeholder={`Reward for level ${l}`}/><span>{level>=l?'Unlocked':'Locked'}</span></div>)}</div>;
return <div className='app'><header><h1>Habit Reset</h1><p>Sleep first. Build points by showing up.</p></header><main>{content}</main><nav>{tabs.map(t=><button key={t.key} onClick={()=>setTab(t.key)} className={tab===t.key?'active':''}>{t.label}</button>)}</nav></div>}
createRoot(document.getElementById('root')!).render(<App/>);
